meta:
  extract_upstream: false
tasks:
  - source: tasks.read_data.save_data
    name: data_saving
    product:
      data_train: products/data/raw_train_data.csv
      data_validation: products/data/raw_validation_data.csv
    params:
      symbols: VIDTUSDT
      start_str: 2022-03-1
  - source: tasks/process_data.ipynb
    upstream: [data_saving]
    name: data_processing
    params:
      initial_return_thresh: 0.5
    product:
      nb: products/notebooks/process_data.ipynb
      data_train: products/data/processed_train_data.csv
      data_validation: products/data/processed_validation_data.csv
  - source: tasks/train_model.ipynb
    upstream: [data_processing]
    name: train_model-
    static_analysis: disable
    product:
      nb: products/notebooks/report.ipynb
    grid:
      - model: xgboost.XGBClassifier
        threshold: [0.5]
        eval_metric: [auc]
        objective: [binary:logistic]
        params_names: [[threshold, objective, eval_metric]]
        track: '{{track}}'
        mlflow_tracking_uri: '{{mlflow_tracking_uri}}'
    #on_finish: hooks.nb_convert_hook.store_report